# Generated by Django 4.2.2 on 2023-07-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calculator_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computation",
            name="answer",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
