# Generated by Django 4.2.2 on 2023-07-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Computation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_number", models.CharField(max_length=250)),
                ("operation", models.CharField(max_length=250)),
                ("second_number", models.CharField(max_length=250)),
                ("answer", models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
